### ISSUE TITLE
[question]What exactly is timeout_ms ?

### ISSUE THREAD

**Issue by habi498** [Theldus/wsServer#101]
Description
-----------
Hi i was making documentation of project developed using wsServer. When it came to timeout_ms, there is a question. 

When starting a websocket server, a timeout_ms is provided. If it is 1000ms, what does it mean? 

Server waiting that much amount of time between handshake?

**Comment by Theldus** [comment]
Hi @habi498,

Thank you for creating this issue. The `timeout_ms` parameter was added a few years ago, so I had honestly forgotten what it was for. However, below is the rationale behind the `timeout_ms`.

The `timeout_ms` was introduced in PR #54 two years ago following observations made in PR #53. More specifically, it was observed that the `send()` function could get stuck for an indefinite amount of time in two scenarios:

**1:** When the message does not fit into the send buffer, as explained in the [Linux man page](https://man7.org/linux/man-pages/man2/send.2.html):

> When the message does not fit into the send buffer of the socket, send() normally blocks, unless the socket has been placed in nonblocking I/O mode.

**2:** When a client silently disconnects. This can happen for various reasons, such as a client losing its internet connection. With the default timeout of 20 minutes, this means the wsServer could be stuck in a `send()` operation for up to 20 minutes before discovering that a client has disconnected.

The `timeout_ms` parameter allows you to set a maximum wait time for `send()` operations, in order to avoid these issues.

Hope this clarifies things!

**Comment by habi498** [comment]
> The timeout_ms parameter allows you to set a maximum wait time for send() operations

Got it. thanks. 
closing the issue also.
