### ISSUE TITLE
How to run on VSStudio2019

### ISSUE THREAD

**Issue by dengwant** [Theldus/wsServer#107]
I follow the "[Building on Windows](https://github.com/Theldus/wsServer/blob/master/doc/BUILD_WINDOWS.md)" and have compiled the library libws.a successfully. When I integrated it into the project. The compile can pass, but report link error.

Can this library be used in the vs2019？

Thanks！

1>libws.a(ws.c.obj) : error LNK2001: 无法解析的外部符号 __mingw_snprintf
1>libws.a(ws.c.obj) : error LNK2001: 无法解析的外部符号 pthread_mutex_lock
1>libws.a(ws.c.obj) : error LNK2001: 无法解析的外部符号 pthread_mutex_unlock
1>libws.a(ws.c.obj) : error LNK2001: 无法解析的外部符号 pthread_mutex_init
1>libws.a(ws.c.obj) : error LNK2001: 无法解析的外部符号 pthread_cond_init
1>libws.a(ws.c.obj) : error LNK2001: 无法解析的外部符号 pthread_create

**Comment by Theldus** [comment]
Hi @dengwant,  
It seems you're building your project with MSVC instead of MinGW. Since wsServer relies on certain POSIX functions that aren't natively available on Windows, it only works in POSIX-like environments or with MinGW, which provides the necessary compatibility for Windows.  

That said, because wsServer uses CMake, you can configure your Visual Studio project to build and run using MinGW under the hood.  

I recommend checking out [Using MinGW and Cygwin with Visual C++ and Open Folder](https://devblogs.microsoft.com/cppblog/using-mingw-and-cygwin-with-visual-cpp-and-open-folder/) for detailed instructions on how to set this up. Additionally, you may find [Creating MinGW64 Applications with Visual Studio](https://visualgdb.com/tutorials/mingw/mingw64/) helpful as well.

**Comment by dengwant** [comment]
OK, I got it. Thanks for your suggestion!
