### ISSUE TITLE
Bind to http server

### ISSUE THREAD

**Issue by onos9** [Theldus/wsServer#29]
This is is an awesome work, setting up and running is a breeze, it just does the work, great library sir. 

Please what is the best way of binding this to an http server to also serve html static files, looking at designing a flow similar to express and ws in nodejs. Thanks for such a great work

**Comment by Theldus** [comment]
It's been almost 8 months and I haven't received any reply.

Sorry, but I'm going to close this issue. Feel free to reopen it again with more information or create a new issue.

**Comment by michael-ts** [comment]
@bezaleel22  It's not clear to me what you mean by "setting up and running is a breeze" as for example I compiled and ran the echo example but it's totally *not* clear how to actually use it.  There is an echo.html file in the same directory so one would assume that it serves that file, but apparently not and now reading the above apparently I need to run a separate web server on a totally different port instead of the normal way of running them both on the same port which apparently is not possible here?  
There is really nothing mentioned in the documentation about this that I can see, so it doesn't really seem breezy for me at all!

**Comment by michael-ts** [comment]
@Theldus  Thanks! I did get it working on a separate port and it does work great... just not used to websockets being on a different port than the HTTP server (in the back of my mind I have this notion of a websocket as occurring as an upgrade of an existing HTTP connection so initially it didn't even occur to me that a separate port would even work...)

**Comment by Theldus** [comment]
@michael-ts Yes, the WebSocket protocol is initiated as a 'protocol-upgrade' over HTTP, but this library only handles the WebSocket protocol, not both.

There are several libraries of this type that only handle WebSocket, and wsServer is one of them, sorry if that wasn't clear enough. I'll try to make the README clearer about this.
